version: "3.5"

services:
  consul:
    image: nixery.dev/shell/consul
    network_mode: host
    command: consul agent -dev -client 127.0.0.1
    # ports:
    #   - "8500:8500"
  nomad:
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    network_mode: host
    build:
      dockerfile: nomad.Dockerfile
      context: .
    volumes:
      - ./:/app
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/nomad/data:/tmp/nomad/data
    depends_on:
      - consul
    # ports:
    #   - "4647:4647"
    #   - "4648:4648"
    #   - "4646:4646"
  dns:
    image: debian
    command: sleep 10000
    depends_on:
      - agent

  agent:
    restart: always
    network_mode: host
    image: embly-host-agent:latest
    depends_on:
      - nomad
      - consul
    cap_add:
      - NET_ADMIN
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
