// Code generated by protoc-gen-go. DO NOT EDIT.
// source: agent.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Service struct {
	Name                 string                `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Count                int32                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Containers           map[string]*Container `protobuf:"bytes,3,rep,name=containers,proto3" json:"containers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Service) Reset()         { *m = Service{} }
func (m *Service) String() string { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()    {}
func (*Service) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{0}
}

func (m *Service) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Service.Unmarshal(m, b)
}
func (m *Service) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Service.Marshal(b, m, deterministic)
}
func (m *Service) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Service.Merge(m, src)
}
func (m *Service) XXX_Size() int {
	return xxx_messageInfo_Service.Size(m)
}
func (m *Service) XXX_DiscardUnknown() {
	xxx_messageInfo_Service.DiscardUnknown(m)
}

var xxx_messageInfo_Service proto.InternalMessageInfo

func (m *Service) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Service) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *Service) GetContainers() map[string]*Container {
	if m != nil {
		return m.Containers
	}
	return nil
}

type Container struct {
	Name                 string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Image                string            `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	Cpu                  int32             `protobuf:"varint,3,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory               int32             `protobuf:"varint,4,opt,name=memory,proto3" json:"memory,omitempty"`
	Command              string            `protobuf:"bytes,5,opt,name=command,proto3" json:"command,omitempty"`
	Ports                []*Port           `protobuf:"bytes,6,rep,name=ports,proto3" json:"ports,omitempty"`
	ConnectTo            []string          `protobuf:"bytes,7,rep,name=connect_to,json=connectTo,proto3" json:"connect_to,omitempty"`
	Environment          map[string]string `protobuf:"bytes,8,rep,name=environment,proto3" json:"environment,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Container) Reset()         { *m = Container{} }
func (m *Container) String() string { return proto.CompactTextString(m) }
func (*Container) ProtoMessage()    {}
func (*Container) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{1}
}

func (m *Container) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Container.Unmarshal(m, b)
}
func (m *Container) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Container.Marshal(b, m, deterministic)
}
func (m *Container) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Container.Merge(m, src)
}
func (m *Container) XXX_Size() int {
	return xxx_messageInfo_Container.Size(m)
}
func (m *Container) XXX_DiscardUnknown() {
	xxx_messageInfo_Container.DiscardUnknown(m)
}

var xxx_messageInfo_Container proto.InternalMessageInfo

func (m *Container) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Container) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *Container) GetCpu() int32 {
	if m != nil {
		return m.Cpu
	}
	return 0
}

func (m *Container) GetMemory() int32 {
	if m != nil {
		return m.Memory
	}
	return 0
}

func (m *Container) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func (m *Container) GetPorts() []*Port {
	if m != nil {
		return m.Ports
	}
	return nil
}

func (m *Container) GetConnectTo() []string {
	if m != nil {
		return m.ConnectTo
	}
	return nil
}

func (m *Container) GetEnvironment() map[string]string {
	if m != nil {
		return m.Environment
	}
	return nil
}

type Port struct {
	IsUDP                bool     `protobuf:"varint,1,opt,name=isUDP,proto3" json:"isUDP,omitempty"`
	Number               int32    `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Port) Reset()         { *m = Port{} }
func (m *Port) String() string { return proto.CompactTextString(m) }
func (*Port) ProtoMessage()    {}
func (*Port) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{2}
}

func (m *Port) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Port.Unmarshal(m, b)
}
func (m *Port) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Port.Marshal(b, m, deterministic)
}
func (m *Port) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Port.Merge(m, src)
}
func (m *Port) XXX_Size() int {
	return xxx_messageInfo_Port.Size(m)
}
func (m *Port) XXX_DiscardUnknown() {
	xxx_messageInfo_Port.DiscardUnknown(m)
}

var xxx_messageInfo_Port proto.InternalMessageInfo

func (m *Port) GetIsUDP() bool {
	if m != nil {
		return m.IsUDP
	}
	return false
}

func (m *Port) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

type DeployMeta struct {
	Stdout               []byte   `protobuf:"bytes,1,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr               []byte   `protobuf:"bytes,2,opt,name=stderr,proto3" json:"stderr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeployMeta) Reset()         { *m = DeployMeta{} }
func (m *DeployMeta) String() string { return proto.CompactTextString(m) }
func (*DeployMeta) ProtoMessage()    {}
func (*DeployMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{3}
}

func (m *DeployMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeployMeta.Unmarshal(m, b)
}
func (m *DeployMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeployMeta.Marshal(b, m, deterministic)
}
func (m *DeployMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeployMeta.Merge(m, src)
}
func (m *DeployMeta) XXX_Size() int {
	return xxx_messageInfo_DeployMeta.Size(m)
}
func (m *DeployMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_DeployMeta.DiscardUnknown(m)
}

var xxx_messageInfo_DeployMeta proto.InternalMessageInfo

func (m *DeployMeta) GetStdout() []byte {
	if m != nil {
		return m.Stdout
	}
	return nil
}

func (m *DeployMeta) GetStderr() []byte {
	if m != nil {
		return m.Stderr
	}
	return nil
}

type HealthRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthRequest) Reset()         { *m = HealthRequest{} }
func (m *HealthRequest) String() string { return proto.CompactTextString(m) }
func (*HealthRequest) ProtoMessage()    {}
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{4}
}

func (m *HealthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthRequest.Unmarshal(m, b)
}
func (m *HealthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthRequest.Marshal(b, m, deterministic)
}
func (m *HealthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthRequest.Merge(m, src)
}
func (m *HealthRequest) XXX_Size() int {
	return xxx_messageInfo_HealthRequest.Size(m)
}
func (m *HealthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HealthRequest proto.InternalMessageInfo

type HealthResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthResponse) Reset()         { *m = HealthResponse{} }
func (m *HealthResponse) String() string { return proto.CompactTextString(m) }
func (*HealthResponse) ProtoMessage()    {}
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{5}
}

func (m *HealthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthResponse.Unmarshal(m, b)
}
func (m *HealthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthResponse.Marshal(b, m, deterministic)
}
func (m *HealthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthResponse.Merge(m, src)
}
func (m *HealthResponse) XXX_Size() int {
	return xxx_messageInfo_HealthResponse.Size(m)
}
func (m *HealthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HealthResponse proto.InternalMessageInfo

func (m *HealthResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *HealthResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type DeployRequest struct {
	Services             []*Service `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *DeployRequest) Reset()         { *m = DeployRequest{} }
func (m *DeployRequest) String() string { return proto.CompactTextString(m) }
func (*DeployRequest) ProtoMessage()    {}
func (*DeployRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{6}
}

func (m *DeployRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeployRequest.Unmarshal(m, b)
}
func (m *DeployRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeployRequest.Marshal(b, m, deterministic)
}
func (m *DeployRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeployRequest.Merge(m, src)
}
func (m *DeployRequest) XXX_Size() int {
	return xxx_messageInfo_DeployRequest.Size(m)
}
func (m *DeployRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeployRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeployRequest proto.InternalMessageInfo

func (m *DeployRequest) GetServices() []*Service {
	if m != nil {
		return m.Services
	}
	return nil
}

type DeployResponse struct {
	Meta                 *DeployMeta `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *DeployResponse) Reset()         { *m = DeployResponse{} }
func (m *DeployResponse) String() string { return proto.CompactTextString(m) }
func (*DeployResponse) ProtoMessage()    {}
func (*DeployResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{7}
}

func (m *DeployResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeployResponse.Unmarshal(m, b)
}
func (m *DeployResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeployResponse.Marshal(b, m, deterministic)
}
func (m *DeployResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeployResponse.Merge(m, src)
}
func (m *DeployResponse) XXX_Size() int {
	return xxx_messageInfo_DeployResponse.Size(m)
}
func (m *DeployResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeployResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeployResponse proto.InternalMessageInfo

func (m *DeployResponse) GetMeta() *DeployMeta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func init() {
	proto.RegisterType((*Service)(nil), "pb.Service")
	proto.RegisterMapType((map[string]*Container)(nil), "pb.Service.ContainersEntry")
	proto.RegisterType((*Container)(nil), "pb.Container")
	proto.RegisterMapType((map[string]string)(nil), "pb.Container.EnvironmentEntry")
	proto.RegisterType((*Port)(nil), "pb.Port")
	proto.RegisterType((*DeployMeta)(nil), "pb.DeployMeta")
	proto.RegisterType((*HealthRequest)(nil), "pb.HealthRequest")
	proto.RegisterType((*HealthResponse)(nil), "pb.HealthResponse")
	proto.RegisterType((*DeployRequest)(nil), "pb.DeployRequest")
	proto.RegisterType((*DeployResponse)(nil), "pb.DeployResponse")
}

func init() {
	proto.RegisterFile("agent.proto", fileDescriptor_56ede974c0020f77)
}

var fileDescriptor_56ede974c0020f77 = []byte{
	// 499 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x53, 0xdf, 0x8b, 0xd3, 0x40,
	0x10, 0x26, 0x6d, 0xd3, 0x36, 0x13, 0xdb, 0x3b, 0x97, 0x43, 0x96, 0x8a, 0x47, 0x89, 0x0f, 0xf6,
	0xa9, 0x6a, 0x3d, 0xe4, 0x50, 0x11, 0xd1, 0x3b, 0xf0, 0x41, 0xe1, 0x58, 0xf5, 0xc5, 0x17, 0x49,
	0xd2, 0xa1, 0x16, 0xbb, 0xbb, 0x71, 0x77, 0x53, 0xe8, 0xbf, 0xe6, 0x83, 0x7f, 0x9b, 0xec, 0x8f,
	0xb4, 0xe9, 0xe1, 0xbd, 0xcd, 0x7c, 0x33, 0xdf, 0xcc, 0x7c, 0x5f, 0x36, 0x90, 0xe6, 0x2b, 0x14,
	0x66, 0x5e, 0x29, 0x69, 0x24, 0xe9, 0x54, 0x45, 0xf6, 0x37, 0x82, 0xc1, 0x17, 0x54, 0xdb, 0x75,
	0x89, 0x84, 0x40, 0x4f, 0xe4, 0x1c, 0x69, 0x34, 0x8d, 0x66, 0x09, 0x73, 0x31, 0x39, 0x83, 0xb8,
	0x94, 0xb5, 0x30, 0xb4, 0x33, 0x8d, 0x66, 0x31, 0xf3, 0x09, 0x79, 0x0d, 0x50, 0x4a, 0x61, 0xf2,
	0xb5, 0x40, 0xa5, 0x69, 0x77, 0xda, 0x9d, 0xa5, 0x8b, 0x87, 0xf3, 0xaa, 0x98, 0x87, 0x51, 0xf3,
	0x0f, 0xfb, 0xea, 0xb5, 0x30, 0x6a, 0xc7, 0x5a, 0xed, 0x93, 0x4f, 0x70, 0x72, 0xab, 0x4c, 0x4e,
	0xa1, 0xfb, 0x0b, 0x77, 0x61, 0xb1, 0x0d, 0xc9, 0x63, 0x88, 0xb7, 0xf9, 0xa6, 0x46, 0xb7, 0x37,
	0x5d, 0x8c, 0xec, 0xf0, 0x3d, 0x8b, 0xf9, 0xda, 0xab, 0xce, 0x65, 0x94, 0xfd, 0xe9, 0x40, 0xb2,
	0x2f, 0xdc, 0x25, 0x61, 0xcd, 0xf3, 0x95, 0x1f, 0x95, 0x30, 0x9f, 0xd8, 0x95, 0x65, 0x55, 0xd3,
	0xae, 0x93, 0x65, 0x43, 0xf2, 0x00, 0xfa, 0x1c, 0xb9, 0x54, 0x3b, 0xda, 0x73, 0x60, 0xc8, 0x08,
	0x85, 0x41, 0x29, 0x39, 0xcf, 0xc5, 0x92, 0xc6, 0x6e, 0x42, 0x93, 0x92, 0x73, 0x88, 0x2b, 0xa9,
	0x8c, 0xa6, 0x7d, 0xe7, 0xc0, 0xd0, 0x1e, 0x79, 0x23, 0x95, 0x61, 0x1e, 0x26, 0x8f, 0x9c, 0x4d,
	0x02, 0x4b, 0xf3, 0xc3, 0x48, 0x3a, 0x98, 0x76, 0x67, 0x09, 0x4b, 0x02, 0xf2, 0x55, 0x92, 0x77,
	0x90, 0xa2, 0xd8, 0xae, 0x95, 0x14, 0x1c, 0x85, 0xa1, 0x43, 0x37, 0xe4, 0xfc, 0x48, 0xe9, 0xfc,
	0xfa, 0xd0, 0xe0, 0x9d, 0x6c, 0x53, 0x26, 0x6f, 0xe1, 0xf4, 0x76, 0xc3, 0x7f, 0xbc, 0x3c, 0x6b,
	0x7b, 0x99, 0xb4, 0xcd, 0xbb, 0x80, 0x9e, 0xbd, 0xd7, 0x59, 0xa4, 0xbf, 0x5d, 0xdd, 0x38, 0xd6,
	0x90, 0xf9, 0xc4, 0x1a, 0x22, 0x6a, 0x5e, 0xa0, 0x0a, 0x1f, 0x3f, 0x64, 0xd9, 0x1b, 0x80, 0x2b,
	0xac, 0x36, 0x72, 0xf7, 0x19, 0x4d, 0x6e, 0xbb, 0xb4, 0x59, 0xca, 0xda, 0x38, 0xf2, 0x3d, 0x16,
	0xb2, 0x80, 0xa3, 0xf2, 0x6c, 0x8f, 0xa3, 0x52, 0xd9, 0x09, 0x8c, 0x3e, 0x62, 0xbe, 0x31, 0x3f,
	0x19, 0xfe, 0xae, 0x51, 0x9b, 0xec, 0x25, 0x8c, 0x1b, 0x40, 0x57, 0x52, 0x68, 0xf7, 0x10, 0x4b,
	0xb9, 0xf4, 0x5f, 0x31, 0x66, 0x2e, 0xb6, 0xb2, 0xb8, 0x5e, 0x05, 0x09, 0x36, 0xcc, 0x2e, 0x61,
	0xe4, 0xcf, 0x08, 0x83, 0xc8, 0x13, 0x18, 0x6a, 0xff, 0xfe, 0x34, 0x8d, 0x9c, 0x99, 0x69, 0xeb,
	0x4d, 0xb2, 0x7d, 0x31, 0xbb, 0x80, 0x71, 0xc3, 0x0c, 0x1b, 0x33, 0xe8, 0x71, 0x34, 0xb9, 0xdb,
	0x98, 0x2e, 0xc6, 0x96, 0x76, 0x90, 0xc8, 0x5c, 0x6d, 0xa1, 0x9b, 0x7d, 0xcd, 0xff, 0xf2, 0x1c,
	0xfa, 0x1e, 0x20, 0xf7, 0x0f, 0x84, 0x70, 0xcc, 0x84, 0xb4, 0x21, 0xbf, 0xe5, 0x59, 0x44, 0x9e,
	0x42, 0xdf, 0x6b, 0xf5, 0x94, 0x23, 0x23, 0x3c, 0xe5, 0xd8, 0x8a, 0xf7, 0xbd, 0xef, 0x9d, 0xaa,
	0x28, 0xfa, 0xee, 0x87, 0x7d, 0xf1, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x3f, 0x0f, 0x6a, 0xdc, 0xbf,
	0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DeployServiceClient is the client API for DeployService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DeployServiceClient interface {
	Deploy(ctx context.Context, in *DeployRequest, opts ...grpc.CallOption) (DeployService_DeployClient, error)
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type deployServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDeployServiceClient(cc grpc.ClientConnInterface) DeployServiceClient {
	return &deployServiceClient{cc}
}

func (c *deployServiceClient) Deploy(ctx context.Context, in *DeployRequest, opts ...grpc.CallOption) (DeployService_DeployClient, error) {
	stream, err := c.cc.NewStream(ctx, &_DeployService_serviceDesc.Streams[0], "/pb.DeployService/Deploy", opts...)
	if err != nil {
		return nil, err
	}
	x := &deployServiceDeployClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DeployService_DeployClient interface {
	Recv() (*DeployResponse, error)
	grpc.ClientStream
}

type deployServiceDeployClient struct {
	grpc.ClientStream
}

func (x *deployServiceDeployClient) Recv() (*DeployResponse, error) {
	m := new(DeployResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *deployServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, "/pb.DeployService/Health", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeployServiceServer is the server API for DeployService service.
type DeployServiceServer interface {
	Deploy(*DeployRequest, DeployService_DeployServer) error
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
}

// UnimplementedDeployServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDeployServiceServer struct {
}

func (*UnimplementedDeployServiceServer) Deploy(req *DeployRequest, srv DeployService_DeployServer) error {
	return status.Errorf(codes.Unimplemented, "method Deploy not implemented")
}
func (*UnimplementedDeployServiceServer) Health(ctx context.Context, req *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}

func RegisterDeployServiceServer(s *grpc.Server, srv DeployServiceServer) {
	s.RegisterService(&_DeployService_serviceDesc, srv)
}

func _DeployService_Deploy_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DeployRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DeployServiceServer).Deploy(m, &deployServiceDeployServer{stream})
}

type DeployService_DeployServer interface {
	Send(*DeployResponse) error
	grpc.ServerStream
}

type deployServiceDeployServer struct {
	grpc.ServerStream
}

func (x *deployServiceDeployServer) Send(m *DeployResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _DeployService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeployServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.DeployService/Health",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeployServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DeployService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.DeployService",
	HandlerType: (*DeployServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _DeployService_Health_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Deploy",
			Handler:       _DeployService_Deploy_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "agent.proto",
}
