// Code generated by protoc-gen-go. DO NOT EDIT.
// source: agent.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Service struct {
	Name                 string                `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Count                int32                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Containers           map[string]*Container `protobuf:"bytes,3,rep,name=containers,proto3" json:"containers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Service) Reset()         { *m = Service{} }
func (m *Service) String() string { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()    {}
func (*Service) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{0}
}

func (m *Service) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Service.Unmarshal(m, b)
}
func (m *Service) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Service.Marshal(b, m, deterministic)
}
func (m *Service) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Service.Merge(m, src)
}
func (m *Service) XXX_Size() int {
	return xxx_messageInfo_Service.Size(m)
}
func (m *Service) XXX_DiscardUnknown() {
	xxx_messageInfo_Service.DiscardUnknown(m)
}

var xxx_messageInfo_Service proto.InternalMessageInfo

func (m *Service) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Service) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *Service) GetContainers() map[string]*Container {
	if m != nil {
		return m.Containers
	}
	return nil
}

type Container struct {
	Name                 string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Image                string            `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	Cpu                  int32             `protobuf:"varint,3,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory               int32             `protobuf:"varint,4,opt,name=memory,proto3" json:"memory,omitempty"`
	Command              string            `protobuf:"bytes,5,opt,name=command,proto3" json:"command,omitempty"`
	Ports                []*Port           `protobuf:"bytes,6,rep,name=ports,proto3" json:"ports,omitempty"`
	ConnectTo            []string          `protobuf:"bytes,7,rep,name=connect_to,json=connectTo,proto3" json:"connect_to,omitempty"`
	Environment          map[string]string `protobuf:"bytes,8,rep,name=environment,proto3" json:"environment,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Container) Reset()         { *m = Container{} }
func (m *Container) String() string { return proto.CompactTextString(m) }
func (*Container) ProtoMessage()    {}
func (*Container) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{1}
}

func (m *Container) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Container.Unmarshal(m, b)
}
func (m *Container) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Container.Marshal(b, m, deterministic)
}
func (m *Container) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Container.Merge(m, src)
}
func (m *Container) XXX_Size() int {
	return xxx_messageInfo_Container.Size(m)
}
func (m *Container) XXX_DiscardUnknown() {
	xxx_messageInfo_Container.DiscardUnknown(m)
}

var xxx_messageInfo_Container proto.InternalMessageInfo

func (m *Container) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Container) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *Container) GetCpu() int32 {
	if m != nil {
		return m.Cpu
	}
	return 0
}

func (m *Container) GetMemory() int32 {
	if m != nil {
		return m.Memory
	}
	return 0
}

func (m *Container) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func (m *Container) GetPorts() []*Port {
	if m != nil {
		return m.Ports
	}
	return nil
}

func (m *Container) GetConnectTo() []string {
	if m != nil {
		return m.ConnectTo
	}
	return nil
}

func (m *Container) GetEnvironment() map[string]string {
	if m != nil {
		return m.Environment
	}
	return nil
}

type Port struct {
	IsUDP                bool     `protobuf:"varint,1,opt,name=isUDP,proto3" json:"isUDP,omitempty"`
	Number               int32    `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Port) Reset()         { *m = Port{} }
func (m *Port) String() string { return proto.CompactTextString(m) }
func (*Port) ProtoMessage()    {}
func (*Port) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{2}
}

func (m *Port) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Port.Unmarshal(m, b)
}
func (m *Port) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Port.Marshal(b, m, deterministic)
}
func (m *Port) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Port.Merge(m, src)
}
func (m *Port) XXX_Size() int {
	return xxx_messageInfo_Port.Size(m)
}
func (m *Port) XXX_DiscardUnknown() {
	xxx_messageInfo_Port.DiscardUnknown(m)
}

var xxx_messageInfo_Port proto.InternalMessageInfo

func (m *Port) GetIsUDP() bool {
	if m != nil {
		return m.IsUDP
	}
	return false
}

func (m *Port) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

type DeployMeta struct {
	Stdout               []byte   `protobuf:"bytes,1,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr               []byte   `protobuf:"bytes,2,opt,name=stderr,proto3" json:"stderr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeployMeta) Reset()         { *m = DeployMeta{} }
func (m *DeployMeta) String() string { return proto.CompactTextString(m) }
func (*DeployMeta) ProtoMessage()    {}
func (*DeployMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{3}
}

func (m *DeployMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeployMeta.Unmarshal(m, b)
}
func (m *DeployMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeployMeta.Marshal(b, m, deterministic)
}
func (m *DeployMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeployMeta.Merge(m, src)
}
func (m *DeployMeta) XXX_Size() int {
	return xxx_messageInfo_DeployMeta.Size(m)
}
func (m *DeployMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_DeployMeta.DiscardUnknown(m)
}

var xxx_messageInfo_DeployMeta proto.InternalMessageInfo

func (m *DeployMeta) GetStdout() []byte {
	if m != nil {
		return m.Stdout
	}
	return nil
}

func (m *DeployMeta) GetStderr() []byte {
	if m != nil {
		return m.Stderr
	}
	return nil
}

func init() {
	proto.RegisterType((*Service)(nil), "pb.Service")
	proto.RegisterMapType((map[string]*Container)(nil), "pb.Service.ContainersEntry")
	proto.RegisterType((*Container)(nil), "pb.Container")
	proto.RegisterMapType((map[string]string)(nil), "pb.Container.EnvironmentEntry")
	proto.RegisterType((*Port)(nil), "pb.Port")
	proto.RegisterType((*DeployMeta)(nil), "pb.DeployMeta")
}

func init() {
	proto.RegisterFile("agent.proto", fileDescriptor_56ede974c0020f77)
}

var fileDescriptor_56ede974c0020f77 = []byte{
	// 400 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0x4d, 0x8b, 0xd4, 0x40,
	0x10, 0x25, 0x9f, 0x33, 0xa9, 0xb8, 0xba, 0x34, 0x8b, 0x34, 0x23, 0x2e, 0x61, 0x3c, 0x98, 0x53,
	0x90, 0xd1, 0xc3, 0xa2, 0x22, 0xa2, 0xbb, 0x37, 0x85, 0xa5, 0xd5, 0x8b, 0x17, 0x49, 0xb2, 0xc5,
	0x12, 0x9c, 0xee, 0x0e, 0x9d, 0xce, 0x40, 0xfe, 0x9a, 0x07, 0x7f, 0x9b, 0xf4, 0xc7, 0xcc, 0xc4,
	0x41, 0x6f, 0xf5, 0x5e, 0xd5, 0xab, 0xea, 0x7a, 0x5d, 0x90, 0xd7, 0xf7, 0x28, 0x74, 0xd5, 0x2b,
	0xa9, 0x25, 0x09, 0xfb, 0x66, 0xfd, 0x3b, 0x80, 0xc5, 0x17, 0x54, 0xbb, 0xae, 0x45, 0x42, 0x20,
	0x16, 0x35, 0x47, 0x1a, 0x14, 0x41, 0x99, 0x31, 0x1b, 0x93, 0x0b, 0x48, 0x5a, 0x39, 0x0a, 0x4d,
	0xc3, 0x22, 0x28, 0x13, 0xe6, 0x00, 0x79, 0x03, 0xd0, 0x4a, 0xa1, 0xeb, 0x4e, 0xa0, 0x1a, 0x68,
	0x54, 0x44, 0x65, 0xbe, 0x79, 0x52, 0xf5, 0x4d, 0xe5, 0x5b, 0x55, 0x1f, 0x0f, 0xd9, 0x1b, 0xa1,
	0xd5, 0xc4, 0x66, 0xe5, 0xab, 0x4f, 0xf0, 0xe8, 0x24, 0x4d, 0xce, 0x21, 0xfa, 0x89, 0x93, 0x1f,
	0x6c, 0x42, 0xf2, 0x0c, 0x92, 0x5d, 0xbd, 0x1d, 0xd1, 0xce, 0xcd, 0x37, 0x67, 0xa6, 0xf9, 0x41,
	0xc5, 0x5c, 0xee, 0x75, 0x78, 0x15, 0xac, 0x7f, 0x85, 0x90, 0x1d, 0x12, 0xff, 0x5b, 0xa1, 0xe3,
	0xf5, 0xbd, 0x6b, 0x95, 0x31, 0x07, 0xcc, 0xc8, 0xb6, 0x1f, 0x69, 0x64, 0xd7, 0x32, 0x21, 0x79,
	0x0c, 0x29, 0x47, 0x2e, 0xd5, 0x44, 0x63, 0x4b, 0x7a, 0x44, 0x28, 0x2c, 0x5a, 0xc9, 0x79, 0x2d,
	0xee, 0x68, 0x62, 0x3b, 0xec, 0x21, 0xb9, 0x84, 0xa4, 0x97, 0x4a, 0x0f, 0x34, 0xb5, 0x0e, 0x2c,
	0xcd, 0x23, 0x6f, 0xa5, 0xd2, 0xcc, 0xd1, 0xe4, 0xa9, 0xb5, 0x49, 0x60, 0xab, 0x7f, 0x68, 0x49,
	0x17, 0x45, 0x54, 0x66, 0x2c, 0xf3, 0xcc, 0x57, 0x49, 0xde, 0x43, 0x8e, 0x62, 0xd7, 0x29, 0x29,
	0x38, 0x0a, 0x4d, 0x97, 0xb6, 0xc9, 0xe5, 0x5f, 0x9b, 0x56, 0x37, 0xc7, 0x02, 0xe7, 0xe4, 0x5c,
	0xb2, 0x7a, 0x07, 0xe7, 0xa7, 0x05, 0xff, 0xf0, 0xf2, 0x62, 0xee, 0x65, 0x36, 0x37, 0xef, 0x15,
	0xc4, 0xe6, 0xbd, 0xd6, 0xa2, 0xe1, 0xdb, 0xf5, 0xad, 0x55, 0x2d, 0x99, 0x03, 0xc6, 0x10, 0x31,
	0xf2, 0x06, 0x95, 0xff, 0x7c, 0x8f, 0xd6, 0x6f, 0x01, 0xae, 0xb1, 0xdf, 0xca, 0xe9, 0x33, 0xea,
	0xda, 0x54, 0x0d, 0xfa, 0x4e, 0x8e, 0xda, 0x8a, 0x1f, 0x30, 0x8f, 0x3c, 0x8f, 0xca, 0xa9, 0x1d,
	0x8f, 0x4a, 0x6d, 0xae, 0xe0, 0xcc, 0xa9, 0xf7, 0x67, 0xf7, 0x1c, 0x52, 0x47, 0x90, 0x7c, 0x76,
	0x42, 0xab, 0x87, 0x06, 0x1c, 0xe7, 0xbc, 0x08, 0x3e, 0xc4, 0xdf, 0xc3, 0xbe, 0x69, 0x52, 0x7b,
	0xbc, 0x2f, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0xc9, 0xfd, 0x94, 0x86, 0xcb, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DeployServiceClient is the client API for DeployService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DeployServiceClient interface {
	Deploy(ctx context.Context, in *Service, opts ...grpc.CallOption) (DeployService_DeployClient, error)
}

type deployServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDeployServiceClient(cc grpc.ClientConnInterface) DeployServiceClient {
	return &deployServiceClient{cc}
}

func (c *deployServiceClient) Deploy(ctx context.Context, in *Service, opts ...grpc.CallOption) (DeployService_DeployClient, error) {
	stream, err := c.cc.NewStream(ctx, &_DeployService_serviceDesc.Streams[0], "/pb.DeployService/Deploy", opts...)
	if err != nil {
		return nil, err
	}
	x := &deployServiceDeployClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DeployService_DeployClient interface {
	Recv() (*DeployMeta, error)
	grpc.ClientStream
}

type deployServiceDeployClient struct {
	grpc.ClientStream
}

func (x *deployServiceDeployClient) Recv() (*DeployMeta, error) {
	m := new(DeployMeta)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DeployServiceServer is the server API for DeployService service.
type DeployServiceServer interface {
	Deploy(*Service, DeployService_DeployServer) error
}

// UnimplementedDeployServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDeployServiceServer struct {
}

func (*UnimplementedDeployServiceServer) Deploy(req *Service, srv DeployService_DeployServer) error {
	return status.Errorf(codes.Unimplemented, "method Deploy not implemented")
}

func RegisterDeployServiceServer(s *grpc.Server, srv DeployServiceServer) {
	s.RegisterService(&_DeployService_serviceDesc, srv)
}

func _DeployService_Deploy_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Service)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DeployServiceServer).Deploy(m, &deployServiceDeployServer{stream})
}

type DeployService_DeployServer interface {
	Send(*DeployMeta) error
	grpc.ServerStream
}

type deployServiceDeployServer struct {
	grpc.ServerStream
}

func (x *deployServiceDeployServer) Send(m *DeployMeta) error {
	return x.ServerStream.SendMsg(m)
}

var _DeployService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.DeployService",
	HandlerType: (*DeployServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Deploy",
			Handler:       _DeployService_Deploy_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "agent.proto",
}
